# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  repository_dispatch:
    types: [my-event]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      
      - run: echo ${{ github.event.client_payload.sha }}
      
     
      
      - name: Call script filr
        shell: pwsh
        run: |
               .\welcome.ps1
        
